chore(upgrade): upgrade django to v2.1.7
deferral/ah-django pull request #5
Opened 2019-03-26 15:49 UTC by hogum

#### What does this PR do?
- Upgarde Django to v2.1.7

#### Description of Task to be completed?
 - [X] ensure the codebase uses the latest django features for python3

#### How should this be manually tested?
- Access the repository on github from [here](https://github.com/andela/ah-django)
- Switch to the branch `ch-upgrade-django2-164859737`
- You should be able to see the upgraded django version on the `requiremetns.txt` file

#### Any background context you want to provide?
None

#### What are the relevant pivotal tracker stories?
[#164859737](https://www.pivotaltracker.com/story/show/164859737)

#### Screenshots

2019-03-26 16:02 UTC, jonathanmusila commented
Nice job @hogum

2019-03-28 04:19 UTC, philophilo requested changes

2019-03-28 04:19 UTC, philophilo commented on authors/apps/authentication/backends.py
> +    def __init__(self, arg):
At this point, we can just pass before assuming

2019-03-28 06:39 UTC, philophilo approved these changes
LGTM

2019-03-28 06:40 UTC, merged